### ISSUE TITLE
after multiple imports, page-model components point to non existing pages 

### ISSUE THREAD

**Issue by benogel** [MPAT-eu/mpat-importexport#2]
![selection_059](https://user-images.githubusercontent.com/7150579/39291645-fba9f63e-4933-11e8-9a4d-94fbc46ec607.png)

this only happens after a second Import. I think this has to do with the ongoing page id allocation of wp.

Idea: After the first import, the IDs generated by wp are the same as on the source-MPAT-page. By counting up the IDs, these are correspondingly higher with the second import.

off topic / more a  MPAT (aka MPAT-plugins) issue: it is actually necessary that the source page exists for a page model? (that would save me some trouble while developing a content importer)

**Comment by jcdufourd** [comment]
I have looked at the issue and have the following comments:
- I created a page model instance from a page model, exported it, imported it elsewhere, re-exported it from elsewhere, imported it into a third site: no problem
- there are no links to a page id from neither page model nor page model instance; there is only a field containing, for information only, the *name* of the origin page model
- if the source page does not exist, that changes nothing in the page model
- if the source page model does not exist, that changes nothing in the page model instance
- the image in this issue shows Clone.jsx which has nothing to do with page model ? if this issue is about clone links, then a lot more needs to be said about what is the procedure

**Comment by jcdufourd** [comment]
If this is about a pair of pages that are clone origin and clone user, both pages HAVE to be imported and exported together each time. If not, it is normal that the link is lost.

**Comment by benogel** [comment]
the problem occurred when:
1. MPAT apps with cloned components have been imported.
2. All imported pages have been deleted
3. The MPAT app has been re-imported

**Comment by jcdufourd** [comment]
This is a feature request for mpat-plugins, not a bug of mpat-importexport.
This is solved in branch forgiving_clone of mpat-plugins
